# Generated by Django 2.1.5 on 2019-02-10 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_invite'),
    ]

    operations = [
        migrations.AddField(
            model_name='tguser',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tguser',
            name='is_notified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tguser',
            name='is_subscribed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tguser',
            name='last_checked_email',
            field=models.TextField(default=None, null=True),
        ),
    ]
