# Generated by Django 2.1.7 on 2019-03-24 10:23

from django.db import migrations, models
class Migration(migrations.Migration):
    dependencies = [
        ('backend', '0003_auto_20190210_1844'),
    ]
    operations = [
        migrations.RenameField(
            model_name='tguser',
            old_name='is_subscribed',
            new_name='is_authorized',
        ),
        migrations.AddField(
            model_name='invite',
            name='code',
            field=models.IntegerField(default=False, unique=True),
        ),
    ]