# Generated by Django 2.1.7 on 2019-03-26 19:22
import datetime
from django.db import migrations, models
import django.db.models.deletion
class Migration(migrations.Migration):
    dependencies = [
        ('backend', '0004_auto_20190324_1023'),
    ]
    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('news', models.TextField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='invite',
            name='name',
            field=models.TextField(default=False),
        ),
        migrations.AddField(
            model_name='invite',
            name='surname',
            field=models.TextField(default=False),
        ),
    ]