# Generated by Django 2.1.5 on 2019-03-30 21:57

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_auto_20190326_1922'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.TextField(choices=[('talk', 'доклад'), ('section', 'секция'), ('workshop', 'воркшоп')])),
                ('title', models.TextField()),
                ('speaker', models.TextField(blank=True, default='')),
                ('description', models.TextField(blank=True, default='')),
                ('location', models.TextField(blank=True)),
                ('start', models.DateTimeField(default=datetime.datetime(2019, 5, 10, 12, 0))),
                ('end', models.DateTimeField(blank=True, default=None, null=True)),
                ('section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='backend.Event')),
            ],
        ),
        migrations.AddField(
            model_name='tguser',
            name='state',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
