# Generated by Django 2.1.5 on 2019-04-10 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_auto_20190330_2157'),
    ]

    operations = [
        migrations.AddField(
            model_name='tguser',
            name='has_news_subscription',
            field=models.BooleanField(default=False),
        ),
    ]
