# Generated by Django 2.1.5 on 2019-04-12 13:06

import django.db.models.deletion
from django.db import migrations, models


def link_invites(apps, schema_editor):
    TGUser = apps.get_model('backend', 'TGUser')
    Invite = apps.get_model('backend', 'Invite')

    for user in TGUser.objects.filter(is_authorized=True).all():
        invite = Invite.objects.filter(email=user.last_checked_email).first()
        if invite is None:
            user.is_authorized = False
            user.save()
            print('no invite for user {} with email {}, de-authorizing'.format(user, user.last_checked_email))
        else:
            user.invite = invite
            user.save()


class Migration(migrations.Migration):
    dependencies = [
        ('backend', '0007_tguser_has_news_subscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='tguser',
            name='invite',
            field=models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL,
                                       related_name='tguser', to='backend.Invite'),
        ),
        migrations.RunPython(link_invites)
    ]
