# Generated by Django 2.1.7 on 2019-04-13 11:12
from django.db import migrations, models

class Migration(migrations.Migration):
    dependencies = [
        ('backend', '0008_tguser_invite'),
    ]
    operations = [
        migrations.AddField(
            model_name='tguser',
            name='in_random_beer',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tguser',
            name='in_random_prize',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tguser',
            name='merch_size',
            field=models.TextField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='tguser',
            name='win_random_prize',
            field=models.BooleanField(default=False),
        ),
    ]