# Generated by Django 2.1.7 on 2019-04-14 15:06
from django.db import migrations, models
class Migration(migrations.Migration):
    dependencies = [
        ('backend', '0009_auto_20190413_1112'),
    ]
    operations = [
        migrations.CreateModel(
            name='Prizes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('merch_size', models.TextField(choices=[('XS', 'XS'), ('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL'), ('XXL', 'XXL'), ('XXXL', 'XXXL')])),
                ('quantity', models.IntegerField(default=0)),
            ],
        ),
    ]