# Generated by Django 2.1.7 on 2019-04-15 21:05
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('backend', '0010_prizes'),
    ]
    operations = [
        migrations.AlterField(
            model_name='prizes',
            name='merch_size',
            field=models.TextField(choices=[('XS', 'XS'), ('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL'),
                                            ('XXL', 'XXL')]),
        ),
    ]