# Generated by Django 2.1.7 on 2019-04-20 06:37
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('backend', '0013_auto_20190419_1954'),
    ]
    operations = [
        migrations.AddField(
            model_name='tguser',
            name='on_major',
            field=models.BooleanField(default=False),
        ),
    ]