# Generated by Django 2.1.7 on 2019-05-09 21:25
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('backend', '0015_broadcast_news'),
    ]
    operations = [
        migrations.AddField(
            model_name='tguser',
            name='in_nvidia_jetsone',
            field=models.BooleanField(default=False),
        ),
    ]