# Generated by Django 2.1.5 on 2019-05-09 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0015_broadcast_news'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_type',
            field=models.TextField(choices=[('Business', 'Бизнес'), ('Community', 'Сообщество'), ('Engineering', 'Инжененрия'), ('Industry', 'Индустрия'), ('Science', 'Наука')]),
        ),
        migrations.AlterField(
            model_name='event',
            name='section',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='event',
            name='title',
            field=models.TextField(blank=True, default=''),
        ),
    ]
